### ISSUE TITLE
Quick question (cause there is no disscutions)

### ISSUE THREAD

**Issue by Kief5555** [jaylinski/flockscreen#1]
Hi,

I have 2 quick questions.

1. Will this work on big sur
2. Can you make a quick download please, xcode is 30gb

**Comment by jaylinski** [comment]
@Kief5555 Hi!

1. I did not upgrade to Big Sur yet, so I don't know
2. I'll create a release and attach the compiled app on monday

**Comment by Kief5555** [comment]
Ok thanks!

**Comment by jaylinski** [comment]
I released v0.1.0 with a zip attached: https://github.com/jaylinski/flockscreen/releases/tag/v0.1.0

Let me know if that works for you. I also updated the readme (it missed the deactivate key `j` and some other stuff).

**Comment by Kief5555** [comment]
Alright thanks!
