### ISSUE TITLE
Does not unlock

### ISSUE THREAD

**Issue by Kief5555** [jaylinski/flockscreen#2]
I tried the app, I pressed lock, it locked. Then I pressed "j", but it did not unlock.

**Comment by jaylinski** [comment]
Did you trigger the lock by moving the mouse or entering a key? This app triggers the real lock-screen, so you have to enter your normal password.

If you did not trigger the lock (and your normal desktop is visible) you should be able to unlock with `j`.

If that still doesn't work, please tell me which keyboard-layout (QWERTZ, ...) you are using.

**Comment by Kief5555** [comment]
Ah, Sorry. I thought the app triggers a fake lock screen, and I could just press "J" to unload it.

**Comment by jaylinski** [comment]
No problem.
