### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by Kief5555** [jaylinski/flockscreen#3]
Hi, 

Can I know a way that someone can bypass the fake lock screen?

Thanks, Kief.

**Comment by jaylinski** [comment]
The invisible (fake) screen lock can currently be unlocked by pressing `j`. (Yes, this is hardcoded and the plan is to make this configurable.)

I don't know of any other way to bypass it if the keyboard **and** mouse triggers are active.

**Comment by Kief5555** [comment]
Ok, then this is going to be and issue, when I press "j",it **does not** close the lock

**Comment by Kief5555** [comment]
Also, can I get you on discord?

**Comment by jaylinski** [comment]
> Also, can I get you on discord?

I'm on discord, yes. You can send me your username and I'll write you a DM.

**Comment by Kief5555** [comment]
Kief#2583
